INSERT INTO mafia_rate.Cards (Title) VALUES ('Алиби');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Банзай');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Бронижилет');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Варуй');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Вербовка');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Дзен');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Инь-ян');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Кейко');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Кицунэ');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Кража');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Крот');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Крыса');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Лечение');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Лидер');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Мина');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Нейтральная');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Отставка');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Под Прикрытием');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Подрывник');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Последний Выстрел');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Призрак');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Прослушка');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Разоблачение');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Сенсей');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Смена Роли');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Смертельный Выстрел');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Сюрикен');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Фугу');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Харакири');
INSERT INTO mafia_rate.Cards (Title) VALUES ('Якудза');